export { LoginPage } from './Login'
export { DashboardPage } from './Dashboard'
export { ProfilePage } from './Profile'
export { PayslipsPage } from './Payslips'
export { PayslipDetailPage } from './PayslipDetail'
export { AssetsPage } from './Assets'
export { LeaveIndexPage, ApplyLeavePage, LeaveApplicationDetailPage } from './leave'
export { TaxDeclarationsPage } from './TaxDeclarations'
export { TaxDeclarationDetailPage } from './TaxDeclarationDetail'
export { AnnouncementsPage } from './Announcements'
export { HelpDeskPage } from './HelpDesk'
export { DocumentsPage } from './Documents'
